In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

### Creating Numpy Arrays

In [2]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# dtype
c = np.array([1,2,3],dtype = float)
print(c)

[1. 2. 3.]


In [5]:
#arange
d = np.arange(20)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
# reshape
e = np.arange(20).reshape(4,5)
print(e)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [7]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros(20).reshape(4,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
#np.random
np.random.random((3,4))

array([[0.89796322, 0.69376648, 0.54791679, 0.58073561],
       [0.21916846, 0.57798252, 0.93164821, 0.9962736 ],
       [0.9536254 , 0.77428052, 0.69548942, 0.85219791]])

In [10]:
#np.linspace
np.linspace(10,20,6, dtype = int)

array([10, 12, 14, 16, 18, 20])

### Array Attributes
- ndim 
- shape
- size 
- itemsize
- dtype

In [11]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [12]:
#ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [13]:
#shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [14]:
#size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [15]:
#itemsize
print(a1.itemsize) #prints 4 bcz there is the datatype int32 which takes 4 bytes for each item
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [16]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype
- astype()

In [17]:
a1 = np.arange(20).reshape(4,5)
a1.dtype

dtype('int64')

In [18]:
#astype
a1 = a1.astype(float)
a1.dtype

dtype('float64')

### Array Operation
- Array with scalar
    - Arithmetic (+ , - , * , / , **)
    - Relational (<= , >= , < , > , ==)
- Array with vectors (+ , - , * , / , **)

In [19]:
a1 = np.arange(20).reshape(4,5)
a2 = np.arange(20,40).reshape(4,5)
print(a1)
print(a2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [20]:
# Array with scalar
# Arithmetic

print(a1+2)
print(a1-2)
print(a1*2)
print(a1/2)
print(a1**2)


[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]]
[[-2 -1  0  1  2]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]
[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7. ]
 [7.5 8.  8.5 9.  9.5]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]]


In [21]:
# Relational

print(a1<= 5)
print(a1>=5)
print(a1==7)
print(a1<10)

[[ True  True  True  True  True]
 [ True False False False False]
 [False False False False False]
 [False False False False False]]
[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False False False False]
 [False False  True False False]
 [False False False False False]
 [False False False False False]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]
 [False False False False False]]


In [22]:
# Arrays operation with vectors

print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1**a2)

[[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]]
[[-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]]
[[  0  21  44  69  96]
 [125 156 189 224 261]
 [300 341 384 429 476]
 [525 576 629 684 741]]
[[0.         0.04761905 0.09090909 0.13043478 0.16666667]
 [0.2        0.23076923 0.25925926 0.28571429 0.31034483]
 [0.33333333 0.35483871 0.375      0.39393939 0.41176471]
 [0.42857143 0.44444444 0.45945946 0.47368421 0.48717949]]
[[                   0                    1              4194304
           94143178827      281474976710656]
 [  298023223876953125  4561031516192243712  5059972980857283351
                     0  5756027422282277481]
 [ 5076944270305263616  1349464372445695011                    0
  -4384162009735594355 -6399284375191552000]
 [-7082734255363670225                    0  1322127838466620497
  -7943720547152560128  5848337558264975355]]


----
### Array Functions
- max / min / sum / prod
- mean / median / std / var
- sin / cos / tan
- np.dot
- log / exp
- round / floor / ceil

In [23]:
a1 = np.round(np.random.random((3,3))*100)
a1

array([[ 9., 12., 52.],
       [97.,  7., 36.],
       [69., 51., 34.]])

In [24]:
print(np.sum(a1))
print(np.max(a1))
print(np.min(a1))
print(np.prod(a1))
print(np.max(a1,axis = 0)) # gives the max elem from each column
print(np.max(a1,axis = 1)) # gives the max elem from each row

367.0
97.0
7.0
16424704243584.0
[97. 51. 52.]
[52. 97. 69.]


In [25]:
import numpy as np
a1 = np.arange(1,11)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
import numpy as np

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [27]:
#dot product
dot = np.dot(a1.T,a2)

In [28]:
# floor/ceil/round

np.floor(np.random.random(20))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [29]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [30]:
# extract 2nd 2d array using slicing
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [31]:
#extract [[0,2],[18,20]]

a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])