In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

### Creating Numpy Arrays

In [2]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# dtype
c = np.array([1,2,3],dtype = float)
print(c)

[1. 2. 3.]


In [5]:
#arange
d = np.arange(20)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
# reshape
e = np.arange(20).reshape(4,5)
print(e)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [7]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros(20).reshape(4,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
#np.random
np.random.random((3,4))

array([[0.3520109 , 0.07806396, 0.17334954, 0.24786219],
       [0.87484835, 0.11840331, 0.01039774, 0.78673803],
       [0.70838968, 0.61158098, 0.88896916, 0.14873773]])

In [10]:
#np.linspace
np.linspace(10,20,6, dtype = int)

array([10, 12, 14, 16, 18, 20])

---
### Array Attributes
- ndim 
- shape
- size 
- itemsize
- dtype

In [11]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [12]:
#ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [13]:
#shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [14]:
#size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [15]:
#itemsize
print(a1.itemsize) #prints 4 bcz there is the datatype int32 which takes 4 bytes for each item
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [16]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


---
### Changing Datatype
- astype()

In [17]:
a1 = np.arange(20).reshape(4,5)
a1.dtype

dtype('int64')

In [18]:
#astype
a1 = a1.astype(float)
a1.dtype

dtype('float64')

---
### Array Operation
- Array with scalar
    - Arithmetic (+ , - , * , / , **)
    - Relational (<= , >= , < , > , ==)
- Array with vectors (+ , - , * , / , **)

In [19]:
a1 = np.arange(20).reshape(4,5)
a2 = np.arange(20,40).reshape(4,5)
print(a1)
print(a2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [20]:
# Array with scalar
# Arithmetic

print(a1+2)
print(a1-2)
print(a1*2)
print(a1/2)
print(a1**2)


[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]]
[[-2 -1  0  1  2]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]
[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7. ]
 [7.5 8.  8.5 9.  9.5]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]]


In [21]:
# Relational

print(a1<= 5)
print(a1>=5)
print(a1==7)
print(a1<10)

[[ True  True  True  True  True]
 [ True False False False False]
 [False False False False False]
 [False False False False False]]
[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False False False False]
 [False False  True False False]
 [False False False False False]
 [False False False False False]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]
 [False False False False False]]


In [22]:
# Arrays operation with vectors

print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1**a2)

[[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]]
[[-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]]
[[  0  21  44  69  96]
 [125 156 189 224 261]
 [300 341 384 429 476]
 [525 576 629 684 741]]
[[0.         0.04761905 0.09090909 0.13043478 0.16666667]
 [0.2        0.23076923 0.25925926 0.28571429 0.31034483]
 [0.33333333 0.35483871 0.375      0.39393939 0.41176471]
 [0.42857143 0.44444444 0.45945946 0.47368421 0.48717949]]
[[                   0                    1              4194304
           94143178827      281474976710656]
 [  298023223876953125  4561031516192243712  5059972980857283351
                     0  5756027422282277481]
 [ 5076944270305263616  1349464372445695011                    0
  -4384162009735594355 -6399284375191552000]
 [-7082734255363670225                    0  1322127838466620497
  -7943720547152560128  5848337558264975355]]


----
### Array Functions
- max / min / sum / prod
- mean / median / std / var
- sin / cos / tan
- np.dot
- log / exp
- round / floor / ceil

In [23]:
a1 = np.round(np.random.random((3,3))*100)
a1

array([[58., 62., 29.],
       [67.,  2., 60.],
       [84., 51., 51.]])

In [24]:
# max / min / sum / prod

print(np.sum(a1))
print(np.max(a1))
print(np.min(a1))
print(np.prod(a1))
print(np.max(a1,axis = 0)) # gives the max elem from each column
print(np.max(a1,axis = 1)) # gives the max elem from each row

464.0
84.0
2.0
183186459066240.0
[84. 62. 60.]
[62. 67. 84.]


In [25]:
# mean / median / std / var

print(np.mean(a1))
print(np.var(a1))
print(np.std(a1))
print(np.median(a1))
print(np.max(a1,axis = 0)) # gives the mean of each column
print(np.max(a1,axis = 1)) # gives the mean of each row

51.55555555555556
497.5802469135803
22.30650682903041
58.0
[84. 62. 60.]
[62. 67. 84.]


In [26]:
# sin / cos / tan

np.sin(a1)

array([[ 0.99287265, -0.7391807 , -0.66363388],
       [-0.85551998,  0.90929743, -0.30481062],
       [ 0.73319032,  0.67022918,  0.67022918]])

In [27]:
#dot product
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
dot = np.dot(a1.T,a2)
print(dot)

[[224 236 248 260]
 [272 287 302 317]
 [320 338 356 374]
 [368 389 410 431]]


In [28]:
# log / exp

print(np.log(a1))
print(np.exp(a1))

[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


/tmp/ipykernel_17/924657661.py:3: RuntimeWarning: divide by zero encountered in log
  print(np.log(a1))


In [29]:
# floor/ceil/round

print(np.ceil(a1))
print(np.floor(a1))
print(np.round(np.random.random((4,5))*100))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[32. 56. 60.  3. 14.]
 [77. 63. 99.  3. 21.]
 [82. 93. 40. 62. 66.]
 [ 8. 40. 35. 70. 27.]]


---
### Indexing and Slicing

- Indexing is a[0,2,1...]
- slicing is a[0:2,:,:]

In [30]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [31]:
# extract 2nd 2d array using slicing
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [32]:
#extract [[0,2],[18,20]]

a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [33]:
# extract [[22, 23],[25, 26]]

a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

---
### Iterating
- using nditer()

In [34]:
for i in np.arange(6):
    print(i)

0
1
2
3
4
5


In [35]:
for i in np.arange(6).reshape(3,2):
    print(i)

[0 1]
[2 3]
[4 5]


In [36]:
# using the nditer() which iterates all element from any dimensional array

for i in np.nditer(np.arange(6).reshape(3,2)):
    print(i)

0
1
2
3
4
5


---
### Reshaping
- reshape
- transpose
- ravel

In [37]:
# reshape
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
# transpose
print(a2)
np.transpose(a2)
a2.T #can also use this

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [39]:
# ravel
print(np.ravel(a2)) #converts the matrix into 1d array

[12 13 14 15 16 17 18 19 20 21 22 23]


---
### Stacking
- hstack
- vstack

In [40]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print()
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [41]:
# hstack (horizontal stacking)
np.hstack((a1,a2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [42]:
#vstack (vertical stacking)
np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

---
### Splitting
- Horizontal splitting
- Vertical splitting

In [43]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
# vsplit() - vertical splitting
a11,a12,a13 = np.vsplit(a1,3)
print(a11,a12,a13)

[[0 1 2 3]] [[4 5 6 7]] [[ 8  9 10 11]]


In [45]:
# hsplit() - horizontal splitting
np.hsplit(a1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]